berkeleyconnect/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from website import forms
from website import views

urlpatterns = [
    url(r'^login/', auth_views.login, name='login', kwargs={'redirect_authenticated_user': True}),
    url(r'^register/$', views.MyRegistrationView.as_view(form_class=forms.NewRegistrationForm),
        name='registration_register',
    ),
    url(r'^logout/$',auth_views.logout_then_login, name = 'logout'),
    url(r'^password/reset/confirm/$', auth_views.password_reset_done, name = 'password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name = 'password_reset_confirm'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete, name = 'password_reset_complete'),
    url(r'^', include('registration.backends.hmac.urls')),
    url(r'^', include('landing.urls', namespace='landing')),
    url(r'^', include('website.urls', namespace='website')),
    url(r'^', include('search.urls', namespace='search')),
    url(r'^', include('content.urls', namespace='content')),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns =+ staticfiles_urlpatterns()

if settings.DEBUG and hasattr(settings, 'DEBUG_TOOLBAR_URLS'):
    urlpatterns = settings.DEBUG_TOOLBAR_URLS + urlpatterns

content/urls.py
from django.conf.urls import url
from content.views import *

urlpatterns = [
    url(r'^stories/$', StoryListView.as_view(), name="stories"),
    url(r'^story/(?P<slug>[\w-]+)/$', StoryDetailView.as_view(), name="story_detail", ),
    url(r'^templates/$', ResourceListView.as_view(), name="templates"),
    url(r'^template/(?P<slug>[\w-]+)/$', ResourceDetailView.as_view(), name="template_detail", ),
    url(r'^incorporation/$', IncorporationView.as_view(), name="incorporation"),
    url(r'^picture-autocomplete/$', PictureAutocomplete.as_view(), name='picture-autocomplete', ),
]

search/urls.py
from django.conf.urls import include, url
import search.views as views

urlpatterns = [
    url(r'^search/$', views.SearchView.as_view(template_name='search.html'), name='search'),
    url(r'^search/(?P<page>\d+)/$', views.SearchView.as_view(template_name='search.html'), name='search'),

    url(r'^search/test/$', views.SearchView.as_view(template_name='search_test.html'), name='search_test'),
    url(r'^search/test/(?P<page>\d+)/$', views.SearchView.as_view(template_name='search_test.html'), name='search_test'),
]

content/models.py
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit
from django.urls import reverse


# Create your models here.
class Story(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    published = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)
    header_name = models.CharField(max_length=256, null=True, blank=True)
    header_image = models.ForeignKey('Picture', null=True, blank=True)
    title = models.CharField(max_length=256)
    description = models.TextField(max_length=256)
    content = models.TextField()
    youtube_id = models.CharField(max_length=256, null=True, blank=True)
    detail = models.CharField(max_length=256, null=True, blank = True)
    def get_absolute_url(self):
        return reverse('content:story_detail', kwargs={'slug': self.slug})


class ResourceCategory(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    published = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)
    title = models.CharField(max_length=256)

    def __unicode__(self):
        return self.title


class Resource(models.Model):
    category = models.ForeignKey(ResourceCategory, null=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    published = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)
    image = models.ForeignKey('Picture', null=True, blank=True)
    title = models.CharField(max_length=256)
    url = models.URLField(max_length=2048)
    description = models.TextField(max_length=400)

    def get_absolute_url(self):
        return reverse('content:story_detail', kwargs={'slug': self.slug})


class Picture(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    text_id = models.CharField(max_length=256, null=True, blank=True)
    title = models.CharField(max_length=256)
    image = models.ImageField(upload_to='images/content/')

    def __unicode__(self):
        return self.title

content/forms.py
from dal import autocomplete
from django import forms
from content.models import *


class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = '__all__'
        widgets = {
            'header_image': autocomplete.ModelSelect2(url='content:picture-autocomplete', attrs={'data-html': True})
        }


class CustomChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.title


class ResourceForm(forms.ModelForm):
    category = CustomChoiceField(queryset=ResourceCategory.objects.all())
    image = CustomChoiceField(queryset=Picture.objects.all())

    class Meta:
        model = Resource
        fields = '__all__'

        # widgets = {
        #     'image': autocomplete.ModelSelect2(url='content:picture-autocomplete', attrs={'data-html': True})
        # }

content/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, View

from search.views import JOB_CONTEXT
from content.models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from website.decorators import check_profiles
from django.contrib.auth.decorators import user_passes_test
from django.utils.html import format_html
from dal import autocomplete


# Create your views here.
@method_decorator(check_profiles, 'get')
class StoryListView(LoginRequiredMixin, ListView):
    model = Story
    queryset = Story.objects.filter(published=True).order_by('-created_at')
    template_name = 'content/story_list.html'

    def get_context_data(self, **kwargs):
        context = super(StoryListView, self).get_context_data(**kwargs)
        context.update(JOB_CONTEXT)
        return context


@method_decorator(check_profiles, 'get')
class StoryDetailView(LoginRequiredMixin, DetailView):
    model = Story

    def get_context_data(self, **kwargs):
        context = super(StoryDetailView, self).get_context_data(**kwargs)
        context.update(JOB_CONTEXT)
        return context


@method_decorator(check_profiles, 'get')
class ResourceListView(LoginRequiredMixin, ListView):
    template_name = 'content/resource_list.html'
    def get_queryset(self):
        return ResourceCategory.objects.filter(published=True).order_by('-created_at').all()

    def get_context_data(self, **kwargs):
        context = super(ResourceListView, self).get_context_data(**kwargs)
        context.update(JOB_CONTEXT)
        return context


@method_decorator(check_profiles, 'get')
class ResourceDetailView(LoginRequiredMixin, DetailView):
    model = Resource

    def get_context_data(self, **kwargs):
        context = super(ResourceDetailView, self).get_context_data(**kwargs)
        context.update(JOB_CONTEXT)
        return context


@method_decorator(check_profiles, 'get')
class IncorporationView(LoginRequiredMixin, View):
    template_name = 'content/incorporation_view.html'

    def get_context_data(self, **kwargs):
        context = super(IncorporationView, self).get_context_data(**kwargs)
        context.update(JOB_CONTEXT)
        return context

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


@method_decorator(user_passes_test(lambda u: u.is_superuser), 'get')
class PictureAutocomplete(autocomplete.Select2QuerySetView):
    def get_result_label(self, item):
        # TODO TODO TODO PUT ESCAPING IN THIS WIDGET TO STOP XSS
        return format_html('<div class="auto-select"><div class="image-holder"><img src="{}"></div> {}</div>', item.image.url, item.title)

    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        if not self.request.user.is_authenticated():
            return Picture.objects.none()

        qs = Picture.objects.all()

        if self.q:
            qs = qs.filter(title__istartswith=self.q)

        return qs

content/templates/content/incorporation_view.html
{% extends 'new/base.html' %}
{% load i18n %}
{% load markup_tags %}

{% block title %}
  Incorporate Your Company
{% endblock %}

{% block search_panel %}
  {% if is_mobile %}{{ block.super }}{% endif %}
{% endblock search_panel %}

{% block content %}

  <div class="container-fluid page-header {% if not is_mobile %}single-page-wrapper{% endif %}">
    <div class="row">
      <div class="f-moto pb-5 pt-5">
        <div class="f-moto-shader"></div>
        <div class="f-moto-layout pb-5 pt-5">
          <div class="container">
            <div class="row text-center">
              <div class="col-12">
                <h1 class="f-moto-title mb-4">Incorporate Your Company</h1>
                <h3 class="f-moto-subtitle" style="color: #041E41">This is a limited time (ends in March) referral opportunity to
                  incorporate<br>for a flat $500 with the invitation only Stripe Atlas program.<br>
                  This is what Bear Founders used, it's a good deal.
                </h3>
                <h3 class="f-moto-subtitle"> This allows you to incorporate in Delaware as a C Corp, gives
                    you Amazon Web Services credits of up to $5,000, free Silicon Valley Bank account setup,<br>
                    an Employer identification Number and more!
                </h3>
                <a class="btn btn-lg btn-primary" href="https://atlas.stripe.com/invite/kihoajpi">
                  Register Your Company
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

content/templates/content/resource_detail.html
{% extends 'new/base.html' %}
{% load static from staticfiles %}
{% load i18n %}

{% block title %}
Resource page
{% endblock %}


{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Student Loans Guy</h3>
                    <h5 class="card-subtitle">Idea • 1 Employee</h5>
                </div>
                <img src="{% static 'img/hero.jpg' %}" alt="" class="card-img">
                <div class="card-body">
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad atque deserunt distinctio incidunt nemo nisi obcaecati porro quo, repudiandae sapiente!</p>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock content %}

content/templates/content/resource_list.html
{% extends 'new/base.html' %}
{% load static from staticfiles %}
{% load website_tags %}
{% load i18n %}

{% block title %}
  Resources page
{% endblock %}

{% block search_panel %}
  {% if is_mobile %}{{ block.super }}{% endif %}
{% endblock search_panel %}

{% block content %}

  <div class="container-fluid page-header">
    <div class="row">
      <div class="f-moto pb-5 pt-5">
        <div class="f-moto-shader"></div>
        <nav class="navbar navbar-expand-sm">
          <ul class="navbar-nav mx-auto smooth-scroll">
            {% for category in object_list %}
              <li class="nav-item text-center">
                <a class="nav-link" href="#category-{{ category.id }}">{{ category.title }}</a>
              </li>
            {% endfor %}
          </ul>
        </nav>
        <div class="f-moto-layout pb-5 pt-5">
          <div class="container">
            <div class="row">
              <div class="col-12">
                <h1 class="f-moto-title mb-4 text-center">Startup Templates</h1>
                <h3 class="f-moto-subtitle text-center">Pitch Deck, Contract, NDA templates & more for your startup needs!</h3>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container-fluid categories">
    {% for category in object_list %}
      <div class="row">
        <div id="category-{{ category.id }}" class="col-12 c-title pt-4 pb-3 mb-4">
          <div class="container c-title-inner">
            <h2 class="text-center text-white">{{ category.title }}</h2>
          </div>
        </div>
        <div class="container">
          <div class="row">
            {% for item in category.resource_set.all %}
              <div class="col-sm-12 col-md-6">
                <a class="card mb-4" href="{{ item.url }}" target="_blank">
                  <div class="card-header">
                    <h4 class="card-title text-center mb-0 text-white">
                      {{ item.title }}
                    </h4>
                  </div>
                  <div class="view overlay hm-white-slight">
                    <img src="{{ item.image.image.url }}" alt="{{ item.image.title }}" class="card-img">
                  </div>
                  <div class="card-body">
                    <p class="card-text">
                      {{ item.description }}
                    </p>
                  </div>
                </a>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

{% endblock content %}

content/templates/content/story_detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load markup_tags %}

{% block title %}
    {{ object.title }}
{% endblock %}

{% if is_mobile %}

  {% block mobile_content %}

    <div class="jumbotron min-screen">
      <div class="container ">
        <div class="row well story">
          <div class="col-md-6 centerfy text-center" >
            <h1>
              {{ object.title }}
            </h1>
          </div>
          <div class="col-md-6 centerfy" id="player-col">
            {% if object.youtube_id %}
              <div id="player"></div>
            {% else %}
              <img src="{{ object.header_image.image.url }}" alt="{{ object.header_image.title }}"/>
            {% endif %}
          </div>
        </div>
        <div class="row well story">
          <div class="col-md-12 centerfy">
            {{ object.content|apply_markup:'creole' }}
          </div>
        </div>
      </div>
    </div>

  {% endblock mobile_content %}

{% else %}

  {% block content %}

  <div class="jumbotron min-screen">
    <div class="container">
      <div class="row well story">

          <div class="col-md-12 centerfy text-justify">
            <div class="holder pull-left" id="player-col">
              {% if object.youtube_id %}
                <div id="player"></div>
              {% else %}
                <img src="{{ object.header_image.image.url }}" alt="{{ object.header_image.title }}"/>
              {% endif %}
            </div>

            <h1>
              {{ object.title }}
            </h1>

            {{ object.content|apply_markup:'creole' }}

          </div>

      </div>
    </div>
  </div>

{% endblock content %}

{% endif %}

{% block js %}
  {{ block.super }}
  {% if object.youtube_id %}
    <script src="https://www.youtube.com/iframe_api"></script>

    <script>
    var player;
    var player_width = $('#player-col').innerWidth()-30;
    var player_height = Math.round(player_width / 16 * 9)

    function updateTimerDisplay () {
      // Update current time text display.
      $('#current-time').text(formatTime(player.getCurrentTime()))
      $('#duration').text(formatTime(player.getDuration()))
    }

    function formatTime (time) {
      time = Math.round(time)

      var minutes = Math.floor(time / 60),
        seconds = time - minutes * 60

      seconds = seconds < 10 ? '0' + seconds : seconds

      return minutes + ':' + seconds
    }

    $('#progress-bar').on('mouseup touchend', function (e) {

      // Calculate the new time for the video.
      // new time in seconds = total duration in seconds * ( value of range input / 100 )
      var newTime = player.getDuration() * (e.target.value / 100)

      // Skip video to new time.
      player.seekTo(newTime)

    });

    // This function is called by initialize()
    function updateProgressBar () {
      // Update the value of our progress bar accordingly.
      $('#progress-bar').val((player.getCurrentTime() / player.getDuration()) * 100)
    }

    function initialize(){

        // Update the controls on load
        updateTimerDisplay();
        updateProgressBar();

        // Clear any old interval.
        if (typeof(time_update_interval) !== 'undefined') {
          clearInterval(time_update_interval);
        }

        // Start interval to update elapsed time display and
        // the elapsed part of the progress bar every second.
        time_update_interval = setInterval(function () {
            updateTimerDisplay();
            updateProgressBar();
        }, 1000)

    }

    function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
            width: player_width,
            height: player_height,
            videoId: '{{ object.youtube_id }}',
            playerVars: {
                color: 'white',
            },
            events: {
                onReady: initialize
            }
        });
    }
    </script>

  {% endif %}
{% endblock js %}

content/templates/content/story_list.html
{% extends 'new/base.html' %}
{% load i18n %}
{% load markup_tags %}

{% block title %}
  Bear Founders Stories
{% endblock %}

{% block search_panel %}
  {% if is_mobile %}{{ block.super }}{% endif %}
{% endblock search_panel %}

{% block content %}

  <div class="container-fluid page-header">
    <div class="row">
      <div class="f-moto pb-5 pt-5">
        <div class="f-moto-shader"></div>
        <div class="f-moto-layout pb-5 pt-5">
          <div class="container">
            <div class="row">
              <div class="col-12">
                <h1 class="f-moto-title mb-4 text-center">Community Stories</h1>
                <h3 class="f-moto-subtitle text-center">Hear stories from fellow bears on startups, internships, jobs, successes, failures and more!</h3>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='container-fluid stories'>
    <div class='row'>
      <div class="container">
        <div class="row">

          {% for story in object_list %}

            <div class="col-sm-12 col-md-6">
              <div class="card mb-4 story-card">
                {% if story.youtube_id %}
                  <a href="{{ story.get_absolute_url }}" class="view overlay hm-white-slight">
                      {% if story.header_image %}
                        <img src="{{ story.header_image.image.url }}" alt="{{ story.header_image.image.title }}" class="card-img"/>
                      {% else %}
                        <img src="http://img.youtube.com/vi/{{ story.youtube_id }}/mqdefault.jpg" class="card-img">
                      {% endif %}
                  </a>
{#                  <div class="header-video">#}
{#                    <a class="card-hover" href='{{ story.get_absolute_url }}'>#}
{#                      <div class="video">#}
{#                        {% if story.header_image %}#}
{#                          <img src="{{ story.header_image.image.url }}" alt="{{ story.header_image.image.title }}"/>#}
{#                        {% else %}#}
{#                          <img src="http://img.youtube.com/vi/{{ story.youtube_id }}/mqdefault.jpg">#}
{#                        {% endif %}#}
{#                      </div>#}
{#                    </a>#}
{#                  </div>#}
                {% else %}
                  <a href="{{ story.get_absolute_url }}" class="view overlay hm-white-slight">
                      {% if story.header_image %}
                        <img src="{{ story.header_image.image.url }}" alt="{{ story.header_image.image.title }}" class="card-img"/>
                      {% endif %}
                  </a>

{#                  <a class="card-hover" href='{{ story.get_absolute_url }}'>#}
{#                    <div class="header-bg">#}
{#                      <div class="avatar">#}
{#                        {% if story.header_image %}#}
{#                          <img src="{{ story.header_image.image.url }}" alt="{{ story.header_image.image.title }}"/>#}
{#                        {% endif %}#}
{#                      </div>#}
{#                      <h2 class="text-white">{{ story.header_name }}</h2>#}
{#                    </div>#}
{#                  </a>#}
                {% endif %}
                <div class="card-body text-center">
                    <a class="card-hover" href='{{ story.get_absolute_url }}'>
                      <h3>{{ story.title }}</h3>
                    </a>
                    {{ story.description|apply_markup:'creole' }}
                </div>


{#                <div class="offer-content">#}
{#                  <div class="info">#}
{#                    <a class="card-hover" href='{{ story.get_absolute_url }}'>#}
{#                      <h3>{{ story.title }}</h3>#}
{#                    </a>#}
{#                    <div class="pcomp"></div>#}
{#                  </div>#}
{#                  <div class="description">#}
{#                    {{ story.description|apply_markup:'creole' }}#}
{#                  </div>#}
{#                </div>#}
              </div>
            </div>

          {% endfor %}

        </div>
      </div>

    </div>
  </div>

{% endblock content %}