berkeleyconnect/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from website import forms
from website import views

urlpatterns = [
    url(r'^login/', auth_views.login, name='login', kwargs={'redirect_authenticated_user': True}),
    url(r'^register/$', views.MyRegistrationView.as_view(form_class=forms.NewRegistrationForm),
        name='registration_register',
    ),
    url(r'^logout/$',auth_views.logout_then_login, name = 'logout'),
    url(r'^password/reset/confirm/$', auth_views.password_reset_done, name = 'password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name = 'password_reset_confirm'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete, name = 'password_reset_complete'),
    url(r'^', include('registration.backends.hmac.urls')),
    url(r'^', include('landing.urls', namespace='landing')),
    url(r'^', include('website.urls', namespace='website')),
    url(r'^', include('search.urls', namespace='search')),
    url(r'^', include('content.urls', namespace='content')),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns =+ staticfiles_urlpatterns()

if settings.DEBUG and hasattr(settings, 'DEBUG_TOOLBAR_URLS'):
    urlpatterns = settings.DEBUG_TOOLBAR_URLS + urlpatterns

landing/urls.py
from django.views.generic.base import TemplateView
from django.conf.urls import include, url
from landing.views import landing

urlpatterns = [
    url(r'^$', landing, name="home"),
]

search/urls.py
from django.conf.urls import include, url
import search.views as views

urlpatterns = [
    url(r'^search/$', views.SearchView.as_view(template_name='search.html'), name='search'),
    url(r'^search/(?P<page>\d+)/$', views.SearchView.as_view(template_name='search.html'), name='search'),

    url(r'^search/test/$', views.SearchView.as_view(template_name='search_test.html'), name='search_test'),
    url(r'^search/test/(?P<page>\d+)/$', views.SearchView.as_view(template_name='search_test.html'), name='search_test'),
]

templates/test.html
{% extends 'new/base.html' %}
{% load static from staticfiles %}
{% load i18n %}

{% block title %}
{% trans "Page not found" %}
{% endblock %}

{% block search_panel %}
  {% if is_mobile %}{{ block.super }}{% endif %}
{% endblock search_panel %}

{% block content %}
  <div class="jumbotron jumbotron-fluid error-rise">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="error-code">500</h1>
        </div>
        <div class="col-md-12 error-message">
          Internal server error
        </div>
        <div class="col-md-12">
          <a class="link" href="{% url 'landing:home' %}">home</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}