berkeleyconnect/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from website import forms
from website import views

urlpatterns = [
    url(r'^login/', auth_views.login, name='login', kwargs={'redirect_authenticated_user': True}),
    url(r'^register/$', views.MyRegistrationView.as_view(form_class=forms.NewRegistrationForm),
        name='registration_register',
    ),
    url(r'^logout/$',auth_views.logout_then_login, name = 'logout'),
    url(r'^password/reset/confirm/$', auth_views.password_reset_done, name = 'password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name = 'password_reset_confirm'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete, name = 'password_reset_complete'),
    url(r'^', include('registration.backends.hmac.urls')),
    url(r'^', include('landing.urls', namespace='landing')),
    url(r'^', include('website.urls', namespace='website')),
    url(r'^', include('search.urls', namespace='search')),
    url(r'^', include('content.urls', namespace='content')),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns =+ staticfiles_urlpatterns()

if settings.DEBUG and hasattr(settings, 'DEBUG_TOOLBAR_URLS'):
    urlpatterns = settings.DEBUG_TOOLBAR_URLS + urlpatterns

search/urls.py
from django.conf.urls import include, url
import search.views as views

urlpatterns = [
    url(r'^search/$', views.SearchView.as_view(template_name='search.html'), name='search'),
    url(r'^search/(?P<page>\d+)/$', views.SearchView.as_view(template_name='search.html'), name='search'),

    url(r'^search/test/$', views.SearchView.as_view(template_name='search_test.html'), name='search_test'),
    url(r'^search/test/(?P<page>\d+)/$', views.SearchView.as_view(template_name='search_test.html'), name='search_test'),
]

website/urls.py
# app/urls.py

from django.conf.urls import url
from django.conf.urls import handler404, handler500, handler400
from website import views

urlpatterns = [
    url(r'^profile/update', views.profile_update, name='profile_update'),
    url(r'^startup/update/$', views.startup_update, name='startup_update'),
    url(r'^profile/$', views.user_profile, name='profile'),
    url(r'^startup_profile/$', views.startup_profile, name='startup_profile'),
    url(r'^profiles/(?P<id>\d+)/$', views.get_profile_view, name='get_profile_view'),
    url(r'^startups/(?P<id>\d+)/$', views.get_startup_view, name='get_startup_view'),

    url(r'^register/profile/$', views.profile_step, name="profile_step"),

    url(r'^connect/$', views.connect, name='connect'),
    url(r'^feedback/$', views.feedback, name='feedback'),

    url(r'^settings/$', views.Settings.as_view(), name='settings'),
    url(r'^settings/change_account_status/(?P<status>(enable|disable))$', views.ChangeAccountStatus.as_view(),
        name='change_account_status'),
    url(r'^resend/$', views.resend_activation_email, name='resend'),
    url(r'^settings/delete_profile/$', views.DeleteProfile.as_view(), name='delete_profile'),

    # Test views to fix image thumbnailing issue
    url(r'^profiles/test/(?P<id>\d+)/$', views.get_test_profile_view, name='get_test_profile_view'),

    url(r'^test', views.test, name='test'),
]

# Simple error handlers override
handler404 = views.handler404
handler500 = views.handler500
handler400 = views.handler400

website/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, get_object_or_404, redirect
from django.http import JsonResponse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required, user_passes_test
from django.template import Context
from django.urls import reverse_lazy
from registration.backends.hmac.views import RegistrationView
from django.contrib import messages
from django.utils import timezone
from django.forms.models import inlineformset_factory
from django.urls import reverse
from django import forms as f
from django.db.models import Sum
from django.conf import settings
from django.http import Http404, HttpResponseServerError
from django.core import signing
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from smtplib import SMTPException
from django.core.mail import EmailMultiAlternatives
from urllib.parse import urlparse
import re
from .models import MyUser
from .forms import ResendActivationEmailForm
from django.views.decorators.vary import vary_on_headers
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator

from website import forms
from website import models
from website import profile as prof
from website.decorators import check_profiles, test_mode, set_activity

import base64, uuid
from django.core.files.base import ContentFile


def merge_dicts(*args):
    dc = {}
    for item in args:
        dc.update(item)
    return dc


JOB_CONTEXT = {
    'p_context': [
        ('year', list(prof.YEAR_IN_SCHOOL_CHOICES), {'class': 'label-year', 'name': 'affiliation'}),
        ('major', list(prof.MAJORS), {'class': 'label-major', 'name': 'major'}),
        ('role', list(prof.PRIMARY_ROLE), {'class': 'label-role', 'name': 'role'}),
        ('experience', [('0', 'Has startup experience'), ('1', 'Has funding experience')],
         {'class': 'label-experience'}),
        ('position', [
            ('0', 'Partner'),
            ('1', 'Intern'),
            ('2', 'Part-Time'),
            ('3', 'Full-Time'),
            ('4', 'Freelance')
        ], {'class': 'label-position'}),
        ('hours', list(prof.HOURS_AVAILABLE), {'class': 'label-hours', 'name': 'Available'})
    ],
    'f_context': [
        ('stage', list(prof.STAGE), {'class': 'label-stage'}),
        ('fields', list(prof.CATEGORY), {'class': 'label-field', 'name': 'field'})
    ],
    'job_context': [
        ('category', list(prof.CATEGORY), {'class': 'label-category'}),
        ('level', list(prof.LEVELS), {'class': 'label-level'}),
        ('pay', list(prof.POSITION), {'class': 'label-pay'})
    ]
}


# Create your views here.
@login_required(login_url='login/')
def connect(request):
    if request.is_ajax():
        email_connect_template = 'email/connection.html'
        url = urlparse(request.META.get('HTTP_REFERER'))
        from_startup = re.match(r'.*/startups/.*', url.path) is not None
        if from_startup:
            receiver = get_object_or_404(prof.Founder, pk=request.POST['profile_id'])
        else:
            receiver = get_object_or_404(prof.Profile, pk=request.POST['profile_id'])
        receiver = receiver.user
        sender = request.user
        text = request.POST['text']
        if receiver is not None:
            try:
                type = url = None
                profile_url = ''
                profile_type = request.POST['profile_type']
                if not sender.get_profile_url() is None and (profile_type in ['', 'individual']):
                    type = 'Profile'
                    url = sender.get_profile_url()
                    profile_url = '{fname} {lname}\'s Profile: {url}'.format(
                        url=request.build_absolute_uri(url),
                        fname=sender.first_name,
                        lname=sender.last_name) + "\r\n\r\n"

                if not sender.get_startup_url() is None and (profile_type in ['', 'startup']):
                    type = 'Startup Profile'
                    url = sender.get_startup_url()
                    profile_url = '{fname} {lname}\'s Startup Profile: {url}'.format(
                        url=request.build_absolute_uri(url),
                        fname=sender.first_name,
                        lname=sender.last_name) + "\r\n\r\n"


                html_content = render_to_string(email_connect_template, {
                    'sender': sender,
                    'msg': request.POST['text'],
                    'url': request.build_absolute_uri(url) if not url is None else None,
                    'type': type,
                })
                receiver.email_user(
                    sender.first_name + " " + sender.last_name + " wants to work with you on Bear Founders!",
                    "You have a new connection:\r\n\r\n" +
                    sender.first_name + " " + sender.last_name + " wants to work with you on Bear Founders!\r\n\r\n" +
                    request.POST['text'] + "\r\n\r\n" + profile_url +
                    "REPLY TO: " + sender.email, 'noreply@bearfounders.com', html_content)

                prof.Connection.objects.create(sender=sender, receiver=receiver, to_startup=from_startup, message=text)
                message = "success"

                return HttpResponse(message)
            except SMTPException as err:
                message = err
        else:
            message = 'failure'
        return HttpResponseServerError(message)
    else:
        raise Http404()


@login_required(login_url='login/')
def feedback(request):
    if request.is_ajax() and hasattr(settings, 'DEFAULT_FEEDBACK_EMAIL'):
        html_template = 'email/feedback.html'
        text_template = 'email/feedback.txt'
        sender = request.user
        message = request.POST['message']
        try:
            connection = prof.Connection.objects.create(sender=sender, message=message, feedback=True)
            text_content = render_to_string(text_template, {'message' : message, 'connection': connection}, request)
            html_content = render_to_string(html_template, {'message' : message, 'connection': connection}, request)
            subject = 'Feedback from {} {}'.format(sender.first_name, sender.last_name)
            to = settings.DEFAULT_FEEDBACK_EMAIL
            from_email = sender.email
            msg = EmailMultiAlternatives(subject, text_content, from_email, to)
            if not html_content is None:
                msg.attach_alternative(html_content, 'text/html')
            msg.send()
            message = "success"

            return HttpResponse(message)
        except SMTPException as err:
            message = err

        return HttpResponseServerError(message)
    else:
        raise Http404()


@login_required(login_url='login/')
@check_profiles
@set_activity
@vary_on_headers('User-Agent')
def index(request):
    return render(request, 'new_home.html',
              merge_dicts(JOB_CONTEXT, {
                  'posted': False,
                  'reset': True,
                  'without_padding': True,
              }))


@login_required
@check_profiles
@set_activity
@never_cache
def user_profile(request):
    last_activity = request.user.last_activity
    current_time = timezone.now()
    cd  = False
    if last_activity is not None:
        cd = current_time.date() == last_activity.date()
    experience = request.user.profile.experience_set.order_by('-end_date')

    # TODO: need to remember normal alg for that
    positions = []
    for item in request.user.profile.positions:
        positions.append(prof.POSITIONS.__getitem__(int(item))[1])

    return render(request, 'profile.html', merge_dicts(JOB_CONTEXT, {
        'profile': True,
        'experience': experience,
        'reset': True,
        'positions_display': positions,
        'cd': cd,
    }))


@login_required
@check_profiles
@set_activity
@never_cache
def startup_profile(request):
    last_activity = request.user.last_activity
    current_time = timezone.now()
    cd  = False
    if last_activity is not None:
        cd = current_time.date() == last_activity.date()
    jobs = request.user.founder.job_set.order_by('created_at')
    total_funding = request.user.founder.funding_set.aggregate(total=Sum('raised'))

    # in case user click on fill out later button in profile update
    # if request.user.first_login:
    #     request.user.set_first_login()

    return render(request, 'founder.html', merge_dicts(JOB_CONTEXT, {
        'profile': True,
        'jobs': jobs,
        'reset': True,
        'total_funding': total_funding.get('total'),
        'cd': cd,
    }))


@login_required
@user_passes_test(lambda user: user.first_login, '/', redirect_field_name=None)
@set_activity
@never_cache
def profile_step(request):
    user = request.user
    formDat = {}
    errors = []
    formDat["hours_available"] = prof.HOURS_AVAILABLE
    formDat["primary_majors"] = prof.MAJORS
    formDat["position_types"] = prof.POSITIONS
    formDat["primary_roles"] = prof.PRIMARY_ROLE
    formDat["cal_affiliation"] = prof.YEAR_IN_SCHOOL_CHOICES
    formDat["startup_history"] = (
        ("has_startup_exp", "I have worked at a startup before"),
        ("has_funding_exp", "I have experience funding a startup")
    )
    formDat["hasStartup"] = (("yes", 'Yes'), ("no", 'No'))
    formDat["is_mentor"] = (
        ((True, 'Yes'), (False, 'No'))
    )

    profile = None if not hasattr(user, 'profile') else user.profile
    if profile is None:
        user = MyUser.objects.get(pk=request.user.id)
        profile = prof.Profile(user=user)

    profile_form = forms.ProfileFormWizard(instance=profile)

    if request.method == 'POST':
        # TODO: Implement Base64EncodedImage form field
        if request.POST.get('image_decoded'):

website/templates/founder_info.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load i18n %}

{% block title %}
{{founder.startup_name}}
{% endblock %}

{% if is_mobile %}

  {% block mobile_content %}
    <div class="profile-page">
      <div class="jumbotron">
        <div class="container">
          <div id="profile-hero" class="row well">
            <div class="col-md-4 centerfy">
              <div class="profile-image text-center img-responsive">
              <div>
                {% if founder.logo %}
                  <img src="{{ founder.logo.url }}" alt="{{ founder.startup_name }}">
                {% else %}
                  <img src="{% static 'images/default/logo.jpg' %}" alt="{{ founder.startup_name }}">
                {% endif %}
              </div>
              </div>
            </div>
            <div class="col-md-8 centerfy">
              <h1>{{ founder.startup_name }}</h1>
              <h3>{{ founder.get_field_display }}</h3>
              <p>{{ founder.get_stage_display }} with {{ founder.employee_count }}
                Employee{{ founder.employee_count|pluralize }}</p>
              <hr>
              {% if cd %}
       				  <h5>Active: Today </h5>
              {%else%}
                <h5>Active: {{ founder.user.last_activity|timesince }} ago</h5>
              {% endif %}
              {% if user.is_founder and user.is_individual %}
              <input type="hidden" id="select_profiles" value="1">
              {% endif %}
              <input type="hidden" id="profile_id" value="{{ founder.pk }}">
              <input type="hidden" id="profile_name" value="{{founder.startup_name|safe}}">
              <button id="connect" class="btn btn-lg btn-primary btn-outline">Contact</button>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col col-md-8 col-md-offset-2">
            <h2>About</h2>
            <p>{{ founder.description|linebreaks }}</p>
            <hr>
          </div>
        </div>
        <div class="row">
          <div class="col col-md-8 col-md-offset-2">
            <h2>Job openings</h2>
            {% for job in jobs %}
              <div class="row">
                <div class="col col-sm-12 well">
                  <h2>{{ job.title }}</h2>
                  <p>{{ job.get_level_display }}</p>
                  {% if job.pay %}
                    <p>{{ job.get_pay_display }}</p>
                  {% endif %}
                  {% if job.description %}
                    <p>{{ job.description|linebreaks }}</p>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <hr>
          </div>
        </div>
        {% if founder.website != "" %}
          <div class="row">
            <div class="col col-md-8 col-md-offset-2">
              <h2>Website</h2>
              <a target="_blank" href={{ founder.website }}>{{ founder.website }}</a>
              <hr>
            </div>
          </div>
        {% endif %}
        {% if founder.facebook != "" %}
          <div class="row">
            <div class="col col-md-8 col-md-offset-2">
              <h2>Facebook</h2>
              <a target="_blank" href={{ founder.facebook }}>{{ founder.facebook }}</a>
              <hr>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  {% endblock %}

{% else %}

  {% block content %}
    <div class="profile-page">
      <div class="jumbotron">
        <div class="container">
          <div id="profile-hero" class="row well">
            <div class="col-md-4 centerfy">
              <div class="profile-image text-center img-responsive">
              <div>
                {% if founder.logo %}
                  <img src="{{ founder.logo.url }}" alt="{{ founder.startup_name }}">
                {% else %}
                  <img src="{% static 'images/default/logo.jpg' %}" alt="{{ founder.startup_name }}">
                {% endif %}
              </div>
              </div>
            </div>
            <div class="col-md-8 centerfy">
              <h1>{{ founder.startup_name }}</h1>
              <h3>{{ founder.get_field_display }}</h3>
              <p>{{ founder.get_stage_display }} with {{ founder.employee_count }}
                Employee{{ founder.employee_count|pluralize }}</p>
              <hr>
              {% if cd %}
       				  <h5>Active: Today </h5>
              {%else%}
                <h5>Active: {{ founder.user.last_activity|timesince }} ago</h5>
              {% endif %}
              {% if user.is_founder and user.is_individual %}
              <input type="hidden" id="select_profiles" value="1">
              {% endif %}
              <input type="hidden" id="profile_id" value="{{ founder.pk }}">
              <input type="hidden" id="profile_name" value="{{founder.startup_name|safe}}">
              <button id="connect" class="btn btn-lg btn-primary btn-outline">Contact</button>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col col-md-8 col-md-offset-2">
            <h2>About</h2>
            <p>{{ founder.description|linebreaks }}</p>
            <hr>
          </div>
        </div>
        <div class="row">
          <div class="col col-md-8 col-md-offset-2">
            <h2>Job openings</h2>
            {% for job in jobs %}
              <div class="row">
                <div class="col col-sm-12 well">
                  <h2>{{ job.title }}</h2>
                  <p>{{ job.get_level_display }}</p>
                  {% if job.pay %}
                    <p>{{ job.get_pay_display }}</p>
                  {% endif %}
                  {% if job.description %}
                    <p>{{ job.description|linebreaks }}</p>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <hr>
          </div>
        </div>
        {% if founder.website != "" %}
          <div class="row">
            <div class="col col-md-8 col-md-offset-2">
              <h2>Website</h2>
              <a target="_blank" href={{ founder.website }}>{{ founder.website }}</a>
              <hr>
            </div>
          </div>
        {% endif %}
        {% if founder.facebook != "" %}
          <div class="row">
            <div class="col col-md-8 col-md-offset-2">
              <h2>Facebook</h2>
              <a target="_blank" href={{ founder.facebook }}>{{ founder.facebook }}</a>
              <hr>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  {% endblock %}

{% endif %}

website/templates/new_home.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel='shortcut icon' type='image/x-icon' href='{% static 'img/favicon.ico' %}?r=1'/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
    <link href="{% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/home.css' %}" rel="stylesheet"/>

    <title>Bear Founders</title>
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top">
            <div class="container">
                <div class="brand-overlay">
                    <a class="navbar-brand" href="/">
                        <span>BEAR FOUNDERS</span>
                    </a>
                </div>
                <div class="dropdown navbar-nav ml-auto">
                    <button class="btn btn-outline-white dropdown-toggle member-name" type="button" href="{% url 'website:profile' %}" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Member</button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        {% if user.is_founder %}
                          <a class="dropdown-item" href="{% url 'website:startup_profile' %}">Startup</a>
                        {% endif %}
                        {% if user.is_individual %}
                          <a class="dropdown-item" href="{% url 'website:profile' %}">Profile</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'website:settings' %}">Settings</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                    </div>
                </div>
            </div>
        </nav>
        <div id="intro" style="background: none;">
            <div class="container-fluid full-bg-img d-flex align-items-center justify-content-center">
                <div class="row d-flex justify-content-center text-center">
                    <div class="col-12 col-md-4">
                        <a href="{% url 'search:search' %}" data-category="startups" class="welcome-links">
                            <div class="card startups img-fluid p-3 mt-3 mb-3">
                                <h1 class="card-title">STARTUPS</h1>
                                <hr class="mt-3 mb-4">
                                <p class="card-text">Discover Innovative Startups</p>
                            </div>
                        </a>
                    </div>
                    <div class="col-12 col-md-4">
                        <a href="{% url 'search:search' %}" data-category="jobs" class="welcome-links">
                            <div class="card jobs img-fluid p-3 mt-3 mb-3">
                                <h1 class="card-title">JOBS</h1>
                                <hr class="mt-3 mb-4">
                                <p class="card-text">Find Meaningful Opportunities</p>
                            </div>
                        </a>
                    </div>
                    <div class="col-12 col-md-4">
                        <a href="{% url 'search:search' %}" data-category="people" class="welcome-links">
                            <div class="card members img-fluid p-3 mt-3 mb-3">
                                <h1 class="card-title">MEMBERS</h1>
                                <hr class="mt-3 mb-4">
                                <p class="card-text">Connect With Teammates</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>


    <script type="text/javascript" src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'dist/umd/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'dist/jquery.waitforimages.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/home.js' %}"></script>
</body>

</html>

website/templates/settings.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %} Settings {% endblock %}

{% if is_mobile %}
  {% block mobile_content %}
    <div class="profile-form">
      <div class="modal-dialog">

        {% if not request.user.is_individual or not request.user.profile %}
          <a href="{% url 'website:profile_update' %}" class="btn btn-primary pull-left" style="margin-right: 20px;">
            Create Personal Profile
          </a>
        {% endif %}

        {% if not request.user.is_founder or not request.user.founder %}
          <a href="{% url 'website:startup_update' %}" class="btn btn-primary pull-left">
            Create Startup Profile
          </a>
        {% endif %}

        <div class="clear20"></div>

        <div id="updateprofile" class="profile-form-container">
          <h1>Change Password</h1><br/>
          <form id="profileform" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="profile-form-submit" value="Update">
          </form>
        </div>

        <div class="clear30"></div>


        <!--repalced by Alternate Contact Email in personal profile update and startup profile update-->
        <!--{% if alternate_email_form %}-->
          <!--<div id="updateprofile" class="profile-form-container">-->
          <!--<h1>Change Alternate Email</h1><br/>-->
          <!--<form id="profileform" method="post" action="{% url 'website:change_alternate_email' %}">-->
          <!--{% csrf_token %}-->
          <!--{{ alternate_email_form|crispy }}-->
          <!--<input type="submit" class="profile-form-submit" value="Update">-->
          <!--</form>-->
          <!--</div>-->
          <!--{% endif %}-->

        <div class="clear30"></div>
        <div class="clear10"></div>

        <div class="pull-left">
          <!--
          If user has both personal and startup profile then show delete profile button with both profiles to select
          from.

          If user has single account i.e personal or startup then simply show disable account button so user can
          disable his account as the user has single profile and deleting that profile doesn't make sense because
          a user is nothing without a profile (personal or startup)
          -->
          {% if request.user.profile and request.user.founder %}
            <form method="post" action="{% url 'website:delete_profile' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary">Delete Selected Profile</button>
              <select name="selected_account" class="select" style="padding: 6px 50px;">
                <option value="personal">Personal Profile</option>
                <option value="startup">Startup Profile</option>
              </select>
            </form>

            <div class="clear30"></div>
            <div class="clear10"></div>

          {% endif %}

          {% if request.user.is_account_disabled %}
            <form method="post" action="{% url 'website:change_account_status' 'enable' %}">{% csrf_token %}</form>
            <button class="btn btn-primary" id="enable-account">Enable Account</button>
          {% else %}
            <form method="post" action="{% url 'website:change_account_status' 'disable' %}">{% csrf_token %}</form>
            <button class="btn btn-primary" id="disable-account">Disable Account</button>
          {% endif %}

        </div>

        <div class="clear30"></div>

      </div>
    </div>

  {% endblock %}
{% else %}

  {% block content %}
    <div class="profile-form">
      <div class="modal-dialog">

        {% if not request.user.is_individual or not request.user.profile %}
          <a href="{% url 'website:profile_update' %}" class="btn btn-primary pull-left" style="margin-right: 20px;">
            Create Personal Profile
          </a>
        {% endif %}

        {% if not request.user.is_founder or not request.user.founder %}
          <a href="{% url 'website:startup_update' %}" class="btn btn-primary pull-left">
            Create Startup Profile
          </a>
        {% endif %}

        <div class="clear20"></div>

        <div id="updateprofile" class="profile-form-container">
          <h1>Change Password</h1><br/>
          <form id="profileform" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="profile-form-submit" value="Update">
          </form>
        </div>

        <div class="clear30"></div>


        <!--repalced by Alternate Contact Email in personal profile update and startup profile update-->
        <!--{% if alternate_email_form %}-->
          <!--<div id="updateprofile" class="profile-form-container">-->
          <!--<h1>Change Alternate Email</h1><br/>-->
          <!--<form id="profileform" method="post" action="{% url 'website:change_alternate_email' %}">-->
          <!--{% csrf_token %}-->
          <!--{{ alternate_email_form|crispy }}-->
          <!--<input type="submit" class="profile-form-submit" value="Update">-->
          <!--</form>-->
          <!--</div>-->
          <!--{% endif %}-->

        <div class="clear30"></div>
        <div class="clear10"></div>

        <div class="pull-left">
          <!--
          If user has both personal and startup profile then show delete profile button with both profiles to select
          from.

          If user has single account i.e personal or startup then simply show disable account button so user can
          disable his account as the user has single profile and deleting that profile doesn't make sense because
          a user is nothing without a profile (personal or startup)
          -->
          {% if request.user.profile and request.user.founder %}
            <form method="post" action="{% url 'website:delete_profile' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary">Delete Selected Profile</button>
              <select name="selected_account" class="select" style="padding: 6px 50px;">
                <option value="personal">Personal Profile</option>
                <option value="startup">Startup Profile</option>
              </select>
            </form>

            <div class="clear30"></div>
            <div class="clear10"></div>

          {% endif %}

          {% if request.user.is_account_disabled %}
            <form method="post" action="{% url 'website:change_account_status' 'enable' %}">{% csrf_token %}</form>
            <button class="btn btn-primary" id="enable-account">Enable Account</button>
          {% else %}
            <form method="post" action="{% url 'website:change_account_status' 'disable' %}">{% csrf_token %}</form>
            <button class="btn btn-primary" id="disable-account">Disable Account</button>
          {% endif %}

        </div>

        <div class="clear30"></div>

      </div>
    </div>

  {% endblock %}

{% endif %}